### ISSUE TITLE
JPG ZIP 檔上傳問題

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-api#172]
指令：
```
$ curl -X POST -F "file=@./Archive.zip"
--cookie ""
https://api-dev.camera-trap.tw/api/v1/files'?'type=annotation-zip'&'cameraLocation=5cd8cafc8c607d2fe0ade34a
```
UploadSession failed:
```
{ 
    "_id" : ObjectId("5cdcfd0218ad1152d679647f"), 
    "state" : "failure", 
    "project" : ObjectId("5cd8c9958c607d84ddade314"), 
    "user" : ObjectId("5cd662cc99580e21fa7fe0e2"), 
    "file" : ObjectId("5cdcfd0218ad11a21579647e"), 
    "cameraLocation" : ObjectId("5cd8cafc8c607d2fe0ade34a"), 
    "createTime" : ISODate("2019-05-16T06:02:42.125+0000"), 
    "updateTime" : ISODate("2019-05-16T06:03:36.928+0000"), 
    "__v" : NumberInt(1), 
    "errorType" : "others"
}
```
Log:
```
{ 
    "_id" : ObjectId("5cdcfd3831ff034327178c47"), 
    "responseStatus" : NumberInt(0), 
    "hostname" : "ip-10-0-1-32.ap-northeast-1.compute.internal", 
    "errorStack" : "Error: spawn /camera-trap-api/node_modules/dist-exiftool/node_modules/exiftool.pl/vendor/exiftool ENOENT\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)\n    at onErrorNT (internal/child_process.js:415:16)\n    at process._tickCallback (internal/process/next_tick.js:63:19)", 
    "extra" : "{\"fileType\":\"annotation-zip\",\"userId\":\"5cd662cc99580e21fa7fe0e2\",\"projectId\":\"5cd8c9958c607d84ddade314\",\"fileId\":\"5cdcfd0218ad11a21579647e\",\"uploadSessionId\":\"5cdcfd0218ad1152d679647f\",\"cameraLocationId\":\"5cd8cafc8c607d2fe0ade34a\"}", 
    "createTime" : ISODate("2019-05-16T06:03:36.849+0000"), 
    "updateTime" : ISODate("2019-05-16T06:03:36.928+0000"), 
    "__v" : NumberInt(0)
}
```

**Comment by kelp404** [comment]
記憶體吃完造成讀 exif 的 process 開不起來。
<img width="1363" alt="螢幕快照 2019-05-16 下午4 04 29" src="https://user-images.githubusercontent.com/1680868/57836937-5b5c1e00-77f4-11e9-81c7-9945333b704d.png">

**Comment by cjk-halodule** [comment]
那也許可以解釋我剛遇到的單筆 JPG 上傳問題：
```
curl \
  -X POST \
  -F "file=@./03150086.JPG" \
  --cookie "" \
  https://api-dev.camera-trap.tw/api/v1/files?type=annotation-image'&'cameraLocation=5cd8cafc8c607d2fe0ade34a | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 6748k  100   111  100 6748k     37  2256k  0:00:03  0:00:02  0:00:01 2256k
```
```
{
  "message": "spawn /camera-trap-api/node_modules/dist-exiftool/node_modules/exiftool.pl/vendor/exiftool ENOENT"
}

**Comment by kelp404** [comment]
問題總共有兩個：
1. alpine 執行 exiftool.pl 會出問題。
2. 記憶體不足。

我用 docker 跑 ubuntu 18，然後 mock AWS S3 是可以上傳成功的。
<img width="724" alt="螢幕快照 2019-05-17 下午12 32 35" src="https://user-images.githubusercontent.com/1680868/57904288-a3d31480-78a4-11e9-9364-1ca3ab8340d4.png">
<img width="741" alt="螢幕快照 2019-05-17 下午12 41 19" src="https://user-images.githubusercontent.com/1680868/57904296-acc3e600-78a4-11e9-83b3-a5f4796658ae.png">

@dca 
我們的 ECS 可以把作業系統從 alpine 換成 ubuntu 嗎？
另外能加 swap 1G 嗎？

**Comment by kelp404** [comment]
我把作業系統換掉後有上傳成功了，剩下爆 memory 的問題，這需要改 Task Definition，一定要加硬碟，然後要省錢的話就是加多一點硬碟開 swap。
規格上 zip 最大可以上傳 5G，機器收了 5G 的 zip 檔，解開後一定超過 10G。

<img width="1211" alt="螢幕快照 2019-05-17 下午6 17 43" src="https://user-images.githubusercontent.com/1680868/57930526-c2f39580-78e8-11e9-8ce7-b96b68aa6064.png">

**Comment by dca** [comment]
我再把那個部分改成 ec2 instance

**Comment by kelp404** [comment]
<img width="368" alt="螢幕快照 2019-05-17 下午9 47 48" src="https://user-images.githubusercontent.com/1680868/57932404-6d6db780-78ed-11e9-8b70-843c32b67e13.png">
之後會將檔案容量限制改為最高 2G。

將 worker 的記憶體調整為 2G，實機測試有上傳成功 300M 的 zip 檔。
<img width="1207" alt="螢幕快照 2019-05-17 下午9 44 47" src="https://user-images.githubusercontent.com/1680868/57932429-7bbbd380-78ed-11e9-8769-f679255bbd9f.png">

**Comment by cjk-halodule** [comment]
看起來檔案上傳後與資料的對應還有問題：
目前 DB 中搜尋 Annotation collection ```{ filename: "03280129.JPG" }```得到三筆：
```
{ 
    "_id" : ObjectId("5cd8fe36b47f6815708fe52a"), 
    "rawData" : [
        "南投縣", 
        "", 
        "草坔01", 
        "03280129.JPG", 
        "2017-03-28 09:58:00", 
        "研究人員", 
        "", 
        "", 
        ""
    ], 
    "failures" : [

    ], 
    "project" : ObjectId("5cd8c9958c607d84ddade314"), 
    "studyArea" : ObjectId("5cd8ca7b8c607d5879ade340"), 
    "cameraLocation" : ObjectId("5cd8cafc8c607d2fe0ade34a"), 
    "uploadSession" : ObjectId("5cd8fe358c607d5545ade7bf"), 
    "filename" : "03280129.JPG", 
    "time" : ISODate("2017-03-28T01:58:00.000+0000"), 
    "species" : ObjectId("5cd8f975b47f6818048fe41f"), 
    "fields" : [

    ], 
    "createTime" : ISODate("2019-05-13T05:18:46.309+0000"), 
    "updateTime" : ISODate("2019-05-14T17:44:19.085+0000"), 
    "state" : "active", 
    "__v" : NumberInt(1)
}
```
是原始 CSV 檔上傳的資料

```
{ 
    "_id" : ObjectId("5cdd24033539cf0746fb51c7"), 
    "rawData" : [

    ], 
    "failures" : [

    ], 
    "project" : ObjectId("5cdcdcd818ad1133db79620f"), 
    "studyArea" : ObjectId("5cdd0cc878bb5000dd873d81"), 
    "cameraLocation" : ObjectId("5cdd0cfa78bb5000dd873d82"), 
    "uploadSession" : ObjectId("5cdd1fdbf65647074718202b"), 
    "file" : ObjectId("5cdeba5f912a95ae42a1f2c1"), 
    "filename" : "03280129.JPG", 
    "time" : ISODate("2017-03-28T01:58:07.000+0000"), 
    "createTime" : ISODate("2019-05-16T08:49:07.479+0000"), 
    "updateTime" : ISODate("2019-05-17T13:43:12.365+0000"), 
    "fields" : [

    ], 
    "state" : "active", 
    "__v" : NumberInt(3)
}
```
是 uploadSession ("_id" : ObjectId("5cdcfd0218ad1152d679647f")) Archive.zip ("_id" : ObjectId("5cdcfd0218ad11a21579647e")) 中的 JPG

```
{ 
    "_id" : ObjectId("5cded968912a95ab9ea1f330"), 
    "rawData" : [

    ], 
    "failures" : [

    ], 
    "project" : ObjectId("5cd8c9958c607d84ddade314"), 
    "studyArea" : ObjectId("5cd8ca7b8c607d5879ade340"), 
    "cameraLocation" : ObjectId("5cd8cafc8c607d2fe0ade34a"), 
    "uploadSession" : ObjectId("5cded9623e1079b37d1fc360"), 
    "file" : ObjectId("5cded9623e107963fe1fc35f"), 
    "filename" : "03280129.JPG", 
    "time" : ISODate("2017-03-28T01:58:07.000+0000"), 
    "createTime" : ISODate("2019-05-17T15:55:20.396+0000"), 
    "updateTime" : ISODate("2019-05-17T15:55:20.400+0000"), 
    "fields" : [

    ], 
    "state" : "active", 
    "__v" : NumberInt(0)
}
```
是下面這個指令送上去的同一檔案：
```
$  curl \
  -X POST \
  -F "file=@./03280129.JPG" \
  --cookie "" \
  https://api-dev.camera-trap.tw/api/v1/files\?type\=annotation-image'&'cameraLocation\=5cd8cafc8c607d2fe0ade34a | jq
```

我把 ```"file" : ObjectId("5cded9623e107963fe1fc35f")``` 插到第一筆文件就可在前端看到影像。
看起來是紀錄的```ISODate("2017-03-28T01:58:00.000+0000")```和照片的```ISODate("2017-03-28T01:58:07.000+0000")```在秒之下的值不同。

這個情形和：
![Screenshot 2019-05-18 00 31 49](https://user-images.githubusercontent.com/31983251/57942604-7cac2f80-7904-11e9-8421-d9ea15677e9f.png)
背後的考慮類似。

所以上傳檔案的對應可以到秒就好，然後用檔名檢查，只要紀錄和上傳的檔案在同一時間（至秒）對得起來，就把 ```"file" : ObjectId("5cded9623e107963fe1fc35f")``` 插到更新到紀錄中？

**Comment by kelp404** [comment]
其中一筆 annotation 是我上傳的，他的 cameraLocation 是測試用計畫底下的。
`"cameraLocation" : ObjectId("5cdd0cfa78bb5000dd873d82"), `
```
{ 
    "_id" : ObjectId("5cdd24033539cf0746fb51c7"), 
    "rawData" : [], 
    "failures" : [], 
    "project" : ObjectId("5cdcdcd818ad1133db79620f"), 
    "studyArea" : ObjectId("5cdd0cc878bb5000dd873d81"), 
    "cameraLocation" : ObjectId("5cdd0cfa78bb5000dd873d82"), 
    "uploadSession" : ObjectId("5cdd1fdbf65647074718202b"), 
    "file" : ObjectId("5cdeba5f912a95ae42a1f2c1"), 
    "filename" : "03280129.JPG", 
    "time" : ISODate("2017-03-28T01:58:07.000+0000"), 
    "createTime" : ISODate("2019-05-16T08:49:07.479+0000"), 
    "updateTime" : ISODate("2019-05-17T13:43:12.365+0000"), 
    "fields" : [

    ], 
    "state" : "active", 
    "__v" : NumberInt(3)
}
```

另外兩筆的問題我覺得是 csv 的時間有問題。
實際上 .jpg 的 exif 是 7 秒，但 csv 所有的紀錄秒數都是零。
<img width="1305" alt="螢幕快照 2019-05-18 上午6 57 28" src="https://user-images.githubusercontent.com/1680868/57960289-7df84f00-793a-11e9-8dd4-ade860ea1547.png">

**Comment by cjk-halodule** [comment]
如果加上檔名對應、時間改成到分鐘一樣就好呢？因為實際情況中，同一相機位置在同一分鐘幾乎不會有檔名相同的碰撞，而我們在清理資料的過程中也陸續發現資料時間和相片時間不完全一致的情況。

**Comment by kelp404** [comment]
是 csv 產生器沒辦法讀到秒嗎？

**Comment by cjk-halodule** [comment]
有一些相機時間因為電池沒電或忘了設定以致於照片的時間會是某年的 1 月 1 日或重設到 1970-01-01 之類的。

csv 產生的流程是先用這個 [windows 軟體](https://www.portablefreeware.com/index.php?id=1171)在下載影像的資料夾產生列表，然後移到 excel 中加上欄位編輯再輸出成 CSV.

**Comment by cjk-halodule** [comment]
```是 csv 產生器沒辦法讀到秒嗎？```
因為之前沒有考慮到大家設備時間的校正和正常使用情況下的偏離（sorry, this is oversight），所以倒不是一開始建立列表時不能產生到秒的資訊，而是事實上所有設備的時間都存在一定範圍的誤差，這個情況應該要再考慮進來。

在理想的情況（相機一直有電，人員也記得確認設定）下，影像上傳時間與資料的對應，我想可以放寬到「分鐘」，因為同一相機位置同一天的檔案名稱幾乎不可能在同一分鐘內有相機重設造成檔案重覆的情況。

至於更大的時間偏離，未來就是透過流程控制。要求使用者先上傳檔案，然後利用系統產生的 CSV 檔，離線編輯後再上傳資料就還是可以完全對應無誤。

**Comment by cjk-halodule** [comment]
討論過的結論是先不改這裡的時間判定，對於時間不準的情況，另建針對單筆 annotation 上傳照片的 endpoint.
